name: "Build-FPSLocker-Warehouse"

on: [push]
env:
  TZ: Asia/Shanghai
jobs:
  Build-FPSLocker-Warehouse:
    name: "Release"
    runs-on: "ubuntu-latest"
    container: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Build & Release"
        run: |
          echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: ./SaltySD ./atmosphere
          filename: 'FPSLocker-Warehouse_${{ env.date }}.zip'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          tag_name: '${{ env.date }}'
          files: 'FPSLocker-Warehouse_${{ env.date }}.zip'
